name: Test Coverage

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # supported python versions can be found here
        # https://github.com/actions/python-versions/releases
        #
        # Please bump to the latest unreleased candidate
        # when you come across this and have a moment to spare!
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10.0-rc.1]
    steps:
    - uses: actions/checkout@master
    - name: set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools
        pip install -U pytest mypy
    - name: run mypy
      run: |
        mypy -p fixed_width --ignore-missing-imports
    - name: Run tests
      run: |
        pytest -v
